"""Add semantic_check_hash to documents

Revision ID: 07131320dd03
Revises: 583e59ebdf92
Create Date: 2026-08-29 11:18:19.920095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07131320dd03'
down_revision: Union[str, Sequence[str], None] = '583e59ebdf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('semantic_check_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'semantic_check_hash')
    # ### end Alembic commands ###
