"""Add embedding columns to documents

Revision ID: 4bfe332579d3
Revises: a44c4b3f6e56
Create Date: 2026-08-19 14:25:19.842604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.embedding_vector


# revision identifiers, used by Alembic.
revision: str = '4bfe332579d3'
down_revision: Union[str, Sequence[str], None] = 'a44c4b3f6e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embedding', app.core.embedding_vector.EmbeddingVector(), nullable=True))
    op.add_column('documents', sa.Column('embedding_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding_updated_at')
    op.drop_column('documents', 'embedding')
    # ### end Alembic commands ###
