"""Create facts table

Revision ID: 5232f552561a
Revises: 6a86d510112c
Create Date: 2026-08-17 21:07:50.053808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5232f552561a'
down_revision: Union[str, Sequence[str], None] = '6a86d510112c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_entity_id', sa.Integer(), nullable=False),
    sa.Column('predicate', sa.String(length=255), nullable=False),
    sa.Column('object_entity_id', sa.Integer(), nullable=True),
    sa.Column('object_value', sa.String(length=1000), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facts')
    # ### end Alembic commands ###
