"""Add llm_facts_hash to documents

Revision ID: 583e59ebdf92
Revises: ba7ac682dbda
Create Date: 2026-08-22 17:23:26.636315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583e59ebdf92'
down_revision: Union[str, Sequence[str], None] = 'ba7ac682dbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('llm_facts_hash', sa.String(length=64), nullable=True))
    op.add_column('facts', sa.Column('object_number', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facts', 'object_number')
    op.drop_column('documents', 'llm_facts_hash')
    # ### end Alembic commands ###
