"""Create conflicts table

Revision ID: a44c4b3f6e56
Revises: 044d1089d705
Create Date: 2026-08-18 12:06:15.647546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44c4b3f6e56'
down_revision: Union[str, Sequence[str], None] = '044d1089d705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='conflictseverity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CONFIRMED', 'DISMISSED', 'EXPLAINED', name='conflictstatus'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('fact_a_id', sa.Integer(), nullable=True),
    sa.Column('fact_b_id', sa.Integer(), nullable=True),
    sa.Column('related_event_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_a_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_b_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conflicts')
    # ### end Alembic commands ###
