"""Add file modified timestamp to documents

Revision ID: a77cdb514fac
Revises: 47dfdbca577a
Create Date: 2026-08-17 13:26:02.053647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77cdb514fac'
down_revision: Union[str, Sequence[str], None] = '47dfdbca577a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_modified_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_modified_at')
    # ### end Alembic commands ###
