"""Add fact source metadata

Revision ID: ba7ac682dbda
Revises: 4bfe332579d3
Create Date: 2026-08-20 01:27:01.943919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7ac682dbda'
down_revision: Union[str, Sequence[str], None] = '4bfe332579d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facts', sa.Column('source_type', sa.String(length=20), server_default='frontmatter', nullable=False))
    op.add_column('facts', sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('facts', sa.Column('source_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facts', 'source_text')
    op.drop_column('facts', 'confidence')
    op.drop_column('facts', 'source_type')
    # ### end Alembic commands ###
